services:
  api-gateway:
    build:
      context: gateway-api/.
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    ports:
      - 8080:8080
    restart: unless-stopped

  order-service-api:
    image: aarfi/order-service-api:latest
    container_name: order-service-api
    ports:
      - 8282:8282
    command: ["java","-jar","order-service-api.jar"]
    restart: unless-stopped

  product-service-api:
    image: aarfi/product-service-api:latest
    container_name: product-service-api
    ports:
      - 8181:8181
    command: ["java","-jar","product-service-api.jar"]
    restart: unless-stopped



